import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path("C:/Users/tkchi/macro_bridge_stack")
AGENT1_DIR = BASE_DIR / "agent1"
AGENT2_DIR = BASE_DIR / "agent2"
OUTPUT_DIR = BASE_DIR

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
OPENROUTER_MODEL = "anthropic/claude-sonnet-4-5"
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

LOOKBACK_DAYS = 90
REQUEST_DELAY = 1.2

FEDERAL_REGISTER_BASE = "https://www.federalregister.gov/api/v1/documents"
USASPENDING_BASE = "https://api.usaspending.gov/api/v2"
PATENTS_BASE = "https://api.patentsview.org/patents/query"
CENSUS_TRADE_BASE = "https://api.census.gov/data"
EDGAR_SUBMISSIONS_BASE = "https://data.sec.gov/submissions"
EDGAR_SEARCH_BASE = "https://efts.sec.gov/LATEST/search-index"
OSHA_BASE = "https://enforcedata.dol.gov/api"
EPA_ECHO_BASE = "https://echo.epa.gov/api"

COMPANIES = [

    # FINANCIALS
    {
        "ticker": "JPM",
        "cik": "19617",
        "name": "JPMorgan Chase & Co",
        "sector": "Financials",
        "fr_terms": ["JPMorgan", "Chase Bank", "bank capital requirements", "systemic risk"],
        "contract_terms": ["JPMorgan Chase", "J.P. Morgan"],
    },
    {
        "ticker": "GS",
        "cik": "886982",
        "name": "Goldman Sachs Group Inc",
        "sector": "Financials",
        "fr_terms": ["Goldman Sachs", "securities dealer regulation", "swap dealer rules"],
        "contract_terms": ["Goldman Sachs"],
    },
    {
        "ticker": "BAC",
        "cik": "70858",
        "name": "Bank of America Corp",
        "sector": "Financials",
        "fr_terms": ["Bank of America", "Community Reinvestment Act", "mortgage servicing standards"],
        "contract_terms": ["Bank of America", "Bank of America NA"],
    },
    {
        "ticker": "TBK",
        "cik": None,
        "name": "Triumph Financial Inc",
        "sector": "Financials",
        "fr_terms": ["freight payment network", "factored receivables", "trucking finance regulation"],
        "contract_terms": ["Triumph Bancorp", "Triumph Financial", "Triumph Business Capital"],
    },
    {
        "ticker": "GBCI",
        "cik": None,
        "name": "Glacier Bancorp Inc",
        "sector": "Financials",
        "fr_terms": ["community bank regulation", "western states banking", "small business lending standards"],
        "contract_terms": ["Glacier Bancorp", "Glacier Bank"],
    },
    {
        "ticker": "PPBI",
        "cik": None,
        "name": "Pacific Premier Bancorp Inc",
        "sector": "Financials",
        "fr_terms": ["commercial real estate lending", "SBA loan program", "community development finance"],
        "contract_terms": ["Pacific Premier Bancorp", "Pacific Premier Bank"],
    },
    {
        "ticker": "CUBI",
        "cik": None,
        "name": "Customers Bancorp Inc",
        "sector": "Financials",
        "fr_terms": ["digital banking regulation", "crypto banking", "institutional deposit rules"],
        "contract_terms": ["Customers Bancorp", "Customers Bank"],
    },
    {
        "ticker": "SBNYP",
        "cik": None,
        "name": "Signature Bank Preferred (OTC -- bank failed March 2023, limited forward data)",
        "sector": "Financials",
        "fr_terms": ["Signature Bank", "FDIC receivership", "New York commercial bank"],
        "contract_terms": ["Signature Bank"],
    },

    # INDUSTRIALS
    {
        "ticker": "CAT",
        "cik": "18230",
        "name": "Caterpillar Inc",
        "sector": "Industrials",
        "fr_terms": ["Caterpillar", "heavy equipment emissions", "diesel engine Tier 5", "infrastructure equipment"],
        "contract_terms": ["Caterpillar Inc", "Caterpillar Financial Products"],
    },
    {
        "ticker": "HON",
        "cik": "773840",
        "name": "Honeywell International Inc",
        "sector": "Industrials",
        "fr_terms": ["Honeywell", "process safety management", "building automation standards", "avionics certification"],
        "contract_terms": ["Honeywell International", "Honeywell Federal Manufacturing", "Honeywell Technology Solutions"],
    },
    {
        "ticker": "MMM",
        "cik": "66740",
        "name": "3M Company",
        "sector": "Industrials",
        "fr_terms": ["3M", "PFAS", "perfluoroalkyl", "occupational exposure limits", "chemical safety OSHA"],
        "contract_terms": ["3M Company", "Minnesota Mining and Manufacturing"],
    },
    {
        "ticker": "IIIN",
        "cik": None,
        "name": "Insteel Industries Inc",
        "sector": "Industrials",
        "fr_terms": ["welded wire mesh", "steel wire", "antidumping circumvention", "wire rod imports", "Section 232 steel"],
        "contract_terms": ["Insteel Industries", "Insteel Wire Products"],
    },
    {
        "ticker": "WTS",
        "cik": None,
        "name": "Watts Water Technologies Inc",
        "sector": "Industrials",
        "fr_terms": ["plumbing safety standards", "backflow prevention", "water efficiency regulation", "lead-free plumbing"],
        "contract_terms": ["Watts Water Technologies", "Watts Regulator"],
    },
    {
        "ticker": "HAYN",
        "cik": None,
        "name": "Haynes International Inc",
        "sector": "Industrials",
        "fr_terms": ["nickel alloy tariff", "high-temperature alloy", "aerospace materials export control"],
        "contract_terms": ["Haynes International", "Haynes Wire Company"],
    },
    {
        "ticker": "MLI",
        "cik": None,
        "name": "Mueller Industries Inc",
        "sector": "Industrials",
        "fr_terms": ["copper products antidumping", "brass fittings regulation", "plumbing fitting standards"],
        "contract_terms": ["Mueller Industries", "Mueller Brass", "Mueller Copper Tube"],
    },
    {
        "ticker": "ZWS",
        "cik": None,
        "name": "Zurn Elkay Water Solutions Corp (replaces RXN -- Rexnord merged into ZWS)",
        "sector": "Industrials",
        "fr_terms": ["water treatment equipment", "lead-free water regulation", "plumbing products standards", "NSF certification water"],
        "contract_terms": ["Zurn Elkay", "Zurn Industries", "Elkay Manufacturing"],
    },
    {
        "ticker": "WOR",
        "cik": None,
        "name": "Worthington Industries Inc",
        "sector": "Industrials",
        "fr_terms": ["steel processing tariff", "pressure cylinder DOT", "propane tank regulation", "hydrogen storage cylinders"],
        "contract_terms": ["Worthington Industries", "Worthington Steel", "Worthington Cylinders"],
    },
    {
        "ticker": "CMC",
        "cik": None,
        "name": "Commercial Metals Company",
        "sector": "Industrials",
        "fr_terms": ["rebar antidumping", "steel reinforcement bar", "Section 232 steel tariff", "wire rod circumvention"],
        "contract_terms": ["Commercial Metals Company", "CMC Steel"],
    },

    # ENERGY
    {
        "ticker": "XOM",
        "cik": "34088",
        "name": "Exxon Mobil Corp",
        "sector": "Energy",
        "fr_terms": ["Exxon", "petroleum refining EPA", "offshore drilling permit", "LNG export authorization"],
        "contract_terms": ["ExxonMobil", "Exxon Mobil Corporation", "ExxonMobil Oil Corporation"],
    },
    {
        "ticker": "CVX",
        "cik": "93410",
        "name": "Chevron Corp",
        "sector": "Energy",
        "fr_terms": ["Chevron", "offshore drilling environmental", "LNG terminal permit", "pipeline safety regulation"],
        "contract_terms": ["Chevron USA", "Chevron Corporation", "Chevron Products Company"],
    },
    {
        "ticker": "SLB",
        "cik": "87347",
        "name": "SLB (Schlumberger NV)",
        "sector": "Energy",
        "fr_terms": ["oilfield services regulation", "well completion technology", "Schlumberger", "drilling technology export"],
        "contract_terms": ["Schlumberger", "SLB", "Smith International"],
    },
    {
        "ticker": "RNGR",
        "cik": None,
        "name": "Ranger Energy Services Inc",
        "sector": "Energy",
        "fr_terms": ["wireline services regulation", "oilfield well services", "hydraulic workover permit"],
        "contract_terms": ["Ranger Energy Services"],
    },
    {
        "ticker": "PUMP",
        "cik": None,
        "name": "ProPetro Holding Corp",
        "sector": "Energy",
        "fr_terms": ["hydraulic fracturing regulation", "pressure pumping EPA", "Permian Basin operations", "frac fluid disclosure"],
        "contract_terms": ["ProPetro Holding", "ProPetro Services"],
    },
    {
        "ticker": "SEI",
        "cik": None,
        "name": "Solaris Energy Infrastructure Inc",
        "sector": "Energy",
        "fr_terms": ["mobile power generation oilfield", "wellsite power supply", "last-mile power energy", "generator fleet oilfield EPA"],
        "contract_terms": ["Solaris Energy Infrastructure", "Solaris Oilfield Infrastructure"],
    },
    {
        "ticker": "WHD",
        "cik": None,
        "name": "Cactus Inc",
        "sector": "Energy",
        "fr_terms": ["wellhead equipment regulation", "pressure control device", "Christmas tree wellhead standards"],
        "contract_terms": ["Cactus Wellhead", "Cactus Inc"],
    },
    {
        "ticker": "CIVI",
        "cik": None,
        "name": "Civitas Resources Inc",
        "sector": "Energy",
        "fr_terms": ["Colorado oil gas regulation", "DJ Basin methane emissions", "oil royalty federal land", "flaring permit Colorado"],
        "contract_terms": ["Civitas Resources", "Bonanza Creek Energy"],
    },

    # DEFENCE AND AEROSPACE
    {
        "ticker": "HEI",
        "cik": None,
        "name": "HEICO Corp",
        "sector": "Defence and Aerospace",
        "fr_terms": ["FAA parts manufacturer approval", "PMA aviation parts", "defense MRO electronics", "aircraft replacement parts FAA"],
        "contract_terms": ["HEICO Corporation", "HEICO Electronic Technologies", "HEICO Parts Group"],
    },
    {
        "ticker": "MRCY",
        "cik": None,
        "name": "Mercury Systems Inc",
        "sector": "Defence and Aerospace",
        "fr_terms": ["embedded computing defense", "ITAR microelectronics", "trusted processing modules", "signal processing defense"],
        "contract_terms": ["Mercury Systems", "Mercury Computer Systems", "Mercury Defense Systems"],
    },
    {
        "ticker": "KTOS",
        "cik": None,
        "name": "Kratos Defense and Security Solutions Inc",
        "sector": "Defence and Aerospace",
        "fr_terms": ["unmanned aerial systems military", "satellite ground system", "hypersonic target drone", "drone defense contract"],
        "contract_terms": ["Kratos Defense", "Kratos Unmanned Aerial Systems", "Kratos Government Solutions"],
    },
    {
        "ticker": "DCO",
        "cik": None,
        "name": "Ducommun Inc",
        "sector": "Defence and Aerospace",
        "fr_terms": ["aerospace structural components", "defense manufacturing contract", "electronic systems aircraft"],
        "contract_terms": ["Ducommun Incorporated", "Ducommun Aerostructures", "Ducommun LaBarge Technologies"],
    },
    {
        "ticker": "MOG.A",
        "cik": None,
        "name": "Moog Inc Class A (NYSE: MOG.A)",
        "sector": "Defence and Aerospace",
        "fr_terms": ["flight control actuation", "missile actuation system", "satellite propulsion", "defense motion control contract"],
        "contract_terms": ["Moog Inc", "Moog Aircraft Group", "Moog Space and Defense"],
    },

    {
        "ticker": "CW",
        "cik": None,
        "name": "Curtiss-Wright Corp",
        "sector": "Defence and Aerospace",
        "fr_terms": ["naval defense electronics", "nuclear instrumentation regulation", "defense actuation systems contract"],
        "contract_terms": ["Curtiss-Wright Corporation", "Curtiss-Wright Defense Solutions", "Curtiss-Wright Controls"],
    },
    {
        "ticker": "ATRO",
        "cik": None,
        "name": "Astronics Corp",
        "sector": "Defence and Aerospace",
        "fr_terms": ["aircraft lighting FAA STC", "in-flight entertainment power systems", "avionics power contract", "military airborne power"],
        "contract_terms": ["Astronics Corporation", "Astronics AES", "Luminescent Systems"],
    },
    {
        "ticker": "TDY",
        "cik": None,
        "name": "Teledyne Technologies Inc (acquired FLIR Systems 2021)",
        "sector": "Defence and Aerospace",
        "fr_terms": ["defense sensors ITAR", "underwater sonar contract", "infrared imaging defense", "FLIR thermal imaging contract"],
        "contract_terms": ["Teledyne Technologies", "Teledyne FLIR", "Teledyne Brown Engineering", "Teledyne Scientific"],
    },

    {
        "ticker": "AVAV",
        "cik": None,
        "name": "AeroVironment Inc",
        "sector": "Defence and Aerospace",
        "fr_terms": ["small unmanned aircraft systems", "tactical drone contract", "loitering munition export", "UAS military contract"],
        "contract_terms": ["AeroVironment Inc", "AeroVironment"],
    },
    {
        "ticker": "SWBI",
        "cik": None,
        "name": "Smith and Wesson Brands Inc",
        "sector": "Defence and Aerospace",
        "fr_terms": ["firearms manufacturing regulation", "small arms ATF", "firearms import duty", "pistol procurement military"],
        "contract_terms": ["Smith & Wesson", "American Outdoor Brands", "Smith and Wesson Brands"],
    },

    # HEALTHCARE AND BIOTECH
    {
        "ticker": "IART",
        "cik": None,
        "name": "Integra LifeSciences Holdings Corp",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["neurosurgery device FDA 510k", "regenerative medicine clearance", "collagen wound matrix FDA", "tissue regeneration device"],
        "contract_terms": ["Integra LifeSciences", "Integra Neurosciences"],
    },
    {
        "ticker": "CSII",
        "cik": None,
        "name": "Cardiovascular Systems Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["atherectomy device FDA PMA", "peripheral vascular device clearance", "orbital atherectomy approval"],
        "contract_terms": ["Cardiovascular Systems Inc", "CSI"],
    },
    {
        "ticker": "ATEC",
        "cik": None,
        "name": "Alphatec Holdings Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["spine implant FDA 510k", "orthopedic device clearance", "lateral access spine system"],
        "contract_terms": ["Alphatec Holdings", "Alphatec Spine"],
    },
    {
        "ticker": "LNTH",
        "cik": None,
        "name": "Lantheus Holdings Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["radiopharmaceutical FDA approval", "PET imaging agent NDA", "nuclear medicine diagnostic", "theranostic drug approval"],
        "contract_terms": ["Lantheus Holdings", "Lantheus Medical Imaging"],
    },
    {
        "ticker": "ENTA",
        "cik": None,
        "name": "Enanta Pharmaceuticals Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["antiviral NDA approval", "hepatitis B treatment FDA", "RSV antiviral drug", "protease inhibitor approval"],
        "contract_terms": ["Enanta Pharmaceuticals"],
    },
    {
        "ticker": "ALEC",
        "cik": None,
        "name": "Alector Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["Alzheimer biologics FDA", "neurodegeneration antibody approval", "immuno-neurology BLA", "TREM2 therapy FDA"],
        "contract_terms": ["Alector Inc"],
    },
    {
        "ticker": "ASRT",
        "cik": None,
        "name": "Assertio Holdings Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["specialty pharmaceutical NDA", "pain management drug approval", "FDA label update specialty"],
        "contract_terms": ["Assertio Holdings", "Assertio Therapeutics"],
    },
    {
        "ticker": "PAHC",
        "cik": None,
        "name": "Phibro Animal Health Corp",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["veterinary drug NADA approval", "animal antibiotic regulation FDA", "livestock feed additive GRAS", "poultry health drug"],
        "contract_terms": ["Phibro Animal Health", "Phibro LLC"],
    },
    {
        "ticker": "AMPH",
        "cik": None,
        "name": "Amphastar Pharmaceuticals Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["injectable generic ANDA FDA", "insulin biosimilar approval", "intranasal drug NDA", "inhalation drug FDA"],
        "contract_terms": ["Amphastar Pharmaceuticals"],
    },
    {
        "ticker": "COLL",
        "cik": None,
        "name": "Collegium Pharmaceutical Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["opioid DEA scheduling", "abuse deterrent opioid FDA", "controlled substance rescheduling", "pain management REMS"],
        "contract_terms": ["Collegium Pharmaceutical"],
    },
    {
        "ticker": "CLPT",
        "cik": None,
        "name": "ClearPoint Neuro Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["MRI-guided neurosurgery FDA", "brain drug delivery device", "neuro navigation clearance FDA", "intracranial therapy device"],
        "contract_terms": ["ClearPoint Neuro", "MRI Interventions"],
    },
    {
        "ticker": "VNDA",
        "cik": None,
        "name": "Vanda Pharmaceuticals Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["circadian rhythm disorder NDA", "melatonin receptor agonist FDA", "psychiatric drug approval FDA"],
        "contract_terms": ["Vanda Pharmaceuticals"],
    },
    {
        "ticker": "RIGL",
        "cik": None,
        "name": "Rigel Pharmaceuticals Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["hematology drug FDA approval", "immune thrombocytopenia BLA", "SYK inhibitor FDA", "autoimmune drug approval"],
        "contract_terms": ["Rigel Pharmaceuticals"],
    },
    {
        "ticker": "NKTR",
        "cik": None,
        "name": "Nektar Therapeutics",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["polymer drug conjugate FDA", "PEGylation technology NDA", "biologic drug delivery approval"],
        "contract_terms": ["Nektar Therapeutics"],
    },
    {
        "ticker": "ACAD",
        "cik": None,
        "name": "ACADIA Pharmaceuticals Inc",
        "sector": "Healthcare and Biotech",
        "fr_terms": ["CNS drug FDA approval", "Parkinson psychosis NDA", "Rett syndrome drug FDA", "5-HT2A inverse agonist approval"],
        "contract_terms": ["ACADIA Pharmaceuticals"],
    },

    # MATERIALS
    {
        "ticker": "IIIN",
        "cik": None,
        "name": "Insteel Industries Inc",
        "sector": "Materials",
        "fr_terms": ["welded wire mesh", "steel wire", "antidumping circumvention", "wire rod imports", "Section 232 steel"],
        "contract_terms": ["Insteel Industries", "Insteel Wire Products"],
    },
    {
        "ticker": "CMC",
        "cik": None,
        "name": "Commercial Metals Company",
        "sector": "Materials",
        "fr_terms": ["rebar antidumping", "steel reinforcement", "Section 232 steel tariff", "wire rod circumvention"],
        "contract_terms": ["Commercial Metals Company", "CMC Steel"],
    },
    {
        "ticker": "WOR",
        "cik": None,
        "name": "Worthington Industries Inc",
        "sector": "Materials",
        "fr_terms": ["steel processing tariff", "pressure cylinder DOT", "hydrogen storage cylinders", "specialty steel coil"],
        "contract_terms": ["Worthington Industries", "Worthington Steel"],
    },
    {
        "ticker": "ZEUS",
        "cik": None,
        "name": "Olympic Steel Inc",
        "sector": "Materials",
        "fr_terms": ["steel service center tariff", "flat-rolled steel import", "Section 232 steel", "specialty metals antidumping"],
        "contract_terms": ["Olympic Steel"],
    },
    {
        "ticker": "HAYN",
        "cik": None,
        "name": "Haynes International Inc",
        "sector": "Materials",
        "fr_terms": ["nickel alloy tariff", "high-temperature alloy export", "aerospace superalloy regulation"],
        "contract_terms": ["Haynes International", "Haynes Wire Company"],
    },
    {
        "ticker": "CMT",
        "cik": None,
        "name": "Core Molding Technologies Inc",
        "sector": "Materials",
        "fr_terms": ["fiberglass composite EPA VOC", "reinforced plastic manufacturing", "thermoset composite regulation"],
        "contract_terms": ["Core Molding Technologies"],
    },
    {
        "ticker": "KWR",
        "cik": None,
        "name": "Quaker Houghton",
        "sector": "Materials",
        "fr_terms": ["metalworking fluid EPA", "specialty chemical safety OSHA", "industrial lubricant regulation", "process fluid REACH"],
        "contract_terms": ["Quaker Houghton", "Quaker Chemical", "Houghton International"],
    },
    {
        "ticker": "AMVAC",
        "cik": None,
        "name": "American Vanguard Corp",
        "sector": "Materials",
        "fr_terms": ["EPA pesticide registration", "pesticide tolerance rule", "organophosphate regulation", "agricultural chemical approval"],
        "contract_terms": ["American Vanguard", "AMVAC Chemical"],
    },
    {
        "ticker": "IOSP",
        "cik": None,
        "name": "Innospec Inc",
        "sector": "Materials",
        "fr_terms": ["fuel additive EPA approval", "aviation gasoline lead additive", "specialty chemical export control", "marine fuel standard"],
        "contract_terms": ["Innospec Inc", "Innospec Fuel Specialties"],
    },
    {
        "ticker": "BCPC",
        "cik": None,
        "name": "Balchem Corp",
        "sector": "Materials",
        "fr_terms": ["FDA GRAS determination", "choline nutrient encapsulation", "specialty gas OSHA permit", "nutritional ingredient FDA"],
        "contract_terms": ["Balchem Corporation", "Balchem Inc"],
    },
    {
        "ticker": "AMSC",
        "cik": None,
        "name": "American Superconductor Corp",
        "sector": "Materials",
        "fr_terms": ["wind turbine technology export", "dual-use export control BIS", "power electronics grid contract", "superconductor ITAR"],
        "contract_terms": ["American Superconductor", "AMSC"],
    },
    {
        "ticker": "TROX",
        "cik": None,
        "name": "Tronox Holdings PLC",
        "sector": "Materials",
        "fr_terms": ["titanium dioxide antidumping", "TiO2 import countervailing duty", "mining EPA permit", "titanium ore processing environmental"],
        "contract_terms": ["Tronox Holdings", "Tronox LLC", "Tronox Pigments"],
    },

    # CONSUMER
    {
        "ticker": "BGFV",
        "cik": None,
        "name": "Big 5 Sporting Goods Corp",
        "sector": "Consumer",
        "fr_terms": ["sporting goods import tariff", "firearms retail ATF", "ammunition import duty"],
        "contract_terms": ["Big 5 Sporting Goods"],
    },
    {
        "ticker": "SPWH",
        "cik": None,
        "name": "Sportsmans Warehouse Holdings Inc",
        "sector": "Consumer",
        "fr_terms": ["outdoor retail ATF firearms", "hunting ammunition regulation", "firearms dealer compliance"],
        "contract_terms": ["Sportsman's Warehouse", "Sportsmans Warehouse"],
    },
    {
        "ticker": "CATO",
        "cik": None,
        "name": "Cato Corp",
        "sector": "Consumer",
        "fr_terms": ["apparel import tariff Section 301", "textile trade regulation", "retail wage standards FLSA"],
        "contract_terms": ["Cato Corporation", "Cato Fashions"],
    },
    {
        "ticker": "DLTH",
        "cik": None,
        "name": "Duluth Trading Company",
        "sector": "Consumer",
        "fr_terms": ["workwear import tariff", "apparel Section 301 tariff", "textile trade rule"],
        "contract_terms": ["Duluth Trading Company"],
    },
    {
        "ticker": "GCO",
        "cik": None,
        "name": "Genesco Inc (replaces HIBB -- Hibbett Sports acquired by JD Sports and delisted June 2023)",
        "sector": "Consumer",
        "fr_terms": ["footwear import tariff", "athletic shoe Section 301", "retail employment WARN notice", "shoe import duty"],
        "contract_terms": ["Genesco Inc", "Journeys", "Johnston Murphy"],
    },

    # TECHNOLOGY
    {
        "ticker": "ITI",
        "cik": None,
        "name": "Iteris Inc",
        "sector": "Technology",
        "fr_terms": ["intelligent transportation DOT", "FHWA smart city contract", "traffic management federal grant", "connected vehicle standard"],
        "contract_terms": ["Iteris Inc"],
    },
    {
        "ticker": "CLFD",
        "cik": None,
        "name": "Clearfield Inc",
        "sector": "Technology",
        "fr_terms": ["BEAD rural broadband FCC", "fiber optic grant NTIA", "broadband deployment infrastructure", "FCC broadband funding"],
        "contract_terms": ["Clearfield Inc", "Clearfield Fiber"],
    },
    {
        "ticker": "PCTI",
        "cik": None,
        "name": "PCTEL Inc",
        "sector": "Technology",
        "fr_terms": ["FCC antenna certification", "5G spectrum allocation", "industrial IoT antenna standard", "FirstNet public safety network"],
        "contract_terms": ["PCTEL Inc"],
    },
    {
        "ticker": "JCS",
        "cik": None,
        "name": "Communications Systems Inc",
        "sector": "Technology",
        "fr_terms": ["military communications contract", "tactical network government", "connectivity infrastructure DOD"],
        "contract_terms": ["Communications Systems Inc", "CSI"],
    },
    {
        "ticker": "OSIS",
        "cik": None,
        "name": "OSI Systems Inc",
        "sector": "Technology",
        "fr_terms": ["TSA security screening contract", "airport inspection system DHS", "cargo security contract CBP", "border security technology"],
        "contract_terms": ["OSI Systems", "Rapiscan Systems", "OSI Systems Inc"],
    },
]
